site_name: Pylon Docs
site_description: Documentation for the Minecraft Pylon plugin
site_author: PylonMC
repo_url: https://github.com/pylonmc/pylon-docs

theme:
  name: material
  logo: img/favicon.png
  favicon: img/favicon.png
  palette:
    scheme: slate
    primary: custom
    accent: cyan
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - content.tabs.link
  icon:
    repo: simple/github

extra:
  social:
    - icon: simple/discord
      link: https://discord.gg/4tMAnBAacW
    - icon: simple/github
      link: https://github.com/pylonmc

extra_css:
  - style.css

nav:
  - What is Pylon?: index.md
  - Installation:
    - Installing Pylon: installation/installing-pylon.md
    - List of addons: installation/list-of-addons.md
    - Commands & permissions: installation/commands-and-permissions.md
  - Creating addons:
    - Getting started: creating-addons/getting-started.md
    - The basics:
      - Adding an item: creating-addons/the-basics/adding-an-item.md
      - Running your addon: creating-addons/the-basics/running-your-addon.md
      - Adding name & lore: creating-addons/the-basics/adding-name-and-lore.md
      - Adding a recipe: creating-addons/the-basics/adding-a-recipe.md
      - Adding a research: creating-addons/the-basics/adding-a-research.md
      - Full code: creating-addons/the-basics/full-code.md
      - Practice tasks: creating-addons/the-basics/practice-tasks.md
    - Custom items:
      - Adding a custom item: creating-addons/custom-items/adding-a-custom-item.md
      - Making items configurable: creating-addons/custom-items/making-items-configurable.md
      - Advanced lore: creating-addons/custom-items/advanced-lore.md
      - Persistent data: creating-addons/custom-items/persistent-data.md
      - A complete example: creating-addons/custom-items/a-complete-example.md
      - Full code: creating-addons/custom-items/full-code.md
      - Practice tasks: creating-addons/custom-items/practice-tasks.md
  - Reference:
    - Data-oriented interfaces: reference/data-oriented-interfaces.md
    - Fluids: reference/fluids.md
    - Cargo: reference/cargo.md
  - Javadocs: javadocs.md
  - Contributing:
    - Getting started: contributing/getting-started.md
    - The Pylon Master Project: contributing/master-project.md
    - Contributing to docs: contributing/contributing-to-docs.md

markdown_extensions:
  - def_list
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition

plugins:
  - open-in-new-tab
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
